# Generated by Django 4.2.10 on 2024-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_modelno', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
