# Generated by Django 4.2.11 on 2024-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_id_profile_img_id_remove_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img_id',
            new_name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_description',
            field=models.TextField(default='null', max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='cat.jpeg', upload_to=''),
        ),
    ]
